### ISSUE TITLE
Composer PHP Dependancy

### ISSUE THREAD

**Issue by jnbn** [faustbrian/Laravel-Categorizable#24]
Getting error - faustbrian/laravel-categorizable 4.0.0 requires php ^7.1 -> your PHP version (7.1.1) on composer install.

Although I still see "php": "^7.0" on requirements I think It would be much better with "php" : ">=7.0.0" if you don't have any special cases.

https://github.com/faustbrian/Laravel-Categorizable/blob/5874c423ed72279ca711e02a7d71edcab0bd0e58/composer.json#L12

**Comment by faustbrian** [comment]
Feel free to send a PR.
