### ISSUE TITLE
Trait 'BrianFaust\Categorizable\Categorizable' not found

### ISSUE THREAD

**Issue by rehmatworks** [faustbrian/Laravel-Categorizable#29]
I'm using Laravel 5.5 on Homestead. Whenever I try to use the trait in a model, it says:
```php
Trait 'BrianFaust\Categorizable\Categorizable' not found
```

I've installed your library via composer. Here is a snippet from my model class:
```php
<?php
namespace App;
use BrianFaust\Categorizable\Categorizable;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
	use Categorizable;
```

Any help will be appreciated greatly.

**Comment by faustbrian** [comment]
`use BrianFaust\Categorizable\Traits\Categorizable;`

**Comment by rehmatworks** [comment]
Oops ;) Didn't notice that. Thanks! I just copied and pasted ;)
